# Generated by Django 3.2 on 2021-07-17 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default=1, max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='web',
            field=models.CharField(default=1, max_length=15),
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=15)),
                ('email_address', models.EmailField(max_length=40)),
                ('zip_code', models.CharField(max_length=6)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('resume', models.FileField(blank=True, default=None, null=True, upload_to='resumes/', verbose_name='resume')),
                ('writeup', models.TextField(blank=True, default=None, max_length=4000, null=True, verbose_name='writeup')),
                ('salary_base', models.IntegerField(blank=True, default=100, null=True, verbose_name='base')),
                ('salary_bonus', models.IntegerField(blank=True, default=20, null=True, verbose_name='bonus')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
        ),
    ]
